module.exports = {
  images: [
    { id: 'backgrounds.main', src: 'assets/images/backgrounds/background.png' },
    { id: 'buttons.1', src: 'assets/images/buttons/ladybug-red-button.png' },
    { id: 'buttons.2', src: 'assets/images/buttons/ladybug-blue-button.png' },
    { id: 'buttons.3', src: 'assets/images/buttons/ladybug-fuchsia-button.png' },
    { id: 'buttons.4', src: 'assets/images/buttons/ladybug-yellow-button.png' },
    { id: 'buttons.5', src: 'assets/images/buttons/ladybug-green-button.png' },
    { id: 'buttons.b', src: 'assets/images/buttons/flower-button.png' },
    { id: 'buttons.default', src: 'assets/images/buttons/fourleaf-button.png' },
    { id: 'icons.info', src: 'assets/images/icons/info-icon.png' },
    { id: 'icons.audio', src: 'assets/images/icons/audio-icon.png' },
    { id: 'statuses.1', src: 'assets/images/statuses/ladybug-red-status.png' },
    { id: 'statuses.2', src: 'assets/images/statuses/ladybug-blue-status.png' },
    { id: 'statuses.3', src: 'assets/images/statuses/ladybug-fuchsia-status.png' },
    { id: 'statuses.4', src: 'assets/images/statuses/ladybug-yellow-status.png' },
    { id: 'statuses.5', src: 'assets/images/statuses/ladybug-green-status.png' },
    { id: 'statuses_table.1', src: 'assets/images/statuses/ladybug-red-status.png' },
    { id: 'statuses_table.2', src: 'assets/images/statuses/ladybug-blue-status.png' },
    { id: 'statuses_table.3', src: 'assets/images/statuses/ladybug-fuchsia-status.png' },
    { id: 'statuses_table.4', src: 'assets/images/statuses/ladybug-yellow-status.png' },
    { id: 'statuses_table.5', src: 'assets/images/statuses/ladybug-green-status.png' },
    { id: 'tiles.1', src: 'assets/images/tiles/ladybug-red-tile.png' },
    { id: 'tiles.2', src: 'assets/images/tiles/ladybug-blue-tile.png' },
    { id: 'tiles.3', src: 'assets/images/tiles/ladybug-fuchsia-tile.png' },
    { id: 'tiles.4', src: 'assets/images/tiles/ladybug-yellow-tile.png' },
    { id: 'tiles.5', src: 'assets/images/tiles/ladybug-green-tile.png' },
    { id: 'images.logo', src: 'assets/images/logo-alpha.png' },
    { id: 'bonus.item.bee', src: 'assets/image/bonus/bonus-item-bee.png' },
    { id: 'bonus.item.ladybug', src: 'assets/images/bonus/bonus-item-ladybug.png' },
    { id: 'bonus.pointer', src: 'assets/images/bonus/bonus-pointer.png' },
    { id: 'bonus.round-fourleaf.brown', src: 'assets/images/bonus/bonus-round-fourleaf-brown.png' },
    { id: 'bonus.round-fourleaf.yellow', src: 'assets/images/bonus/bonus-round-fourleaf-yellow.png' },
    { id: 'bonus.round-fourleaf.green', src: 'assets/images/bonus/bonus-round-fourleaf-green.png' },
  ],
  spritesheets: [
    { id: 'spritesheets.flower-ok', src: 'assets/spritesheets/flower-ok.json' },
    { id: 'spritesheets.ladybug-ok', src: 'assets/spritesheets/ladybug-ok.json' },
    { id: 'spritesheets.ladybug-eyeblink', src: 'assets/spritesheets/ladybug-eyeblink.json' },
  ],
};
