export default {
  preloader: {
    images: [
      { id: 'backgrounds.loading', src: 'assets/images/backgrounds/bg_loading.png' },
      { id: 'loader.logo', src: 'assets/images/loader/loading_text.png' },
      { id: 'loader.lady-bug', src: 'assets/images/loader/lucky_loading.png' },
      { id: 'loader.lady-bug-full', src: 'assets/images/loader/lucky_loading_full.png' },
    ],
  },
  game: {
    images: [
      { id: 'backgrounds.main', src: 'assets/images/backgrounds/background.png' },
      { id: 'backgrounds.outcome', src: 'assets/images/backgrounds/bg_outcome.png' },
      { id: 'backgrounds.cyberpunk', src: 'assets/images/backgrounds/cyberpunk-street.png' },
      { id: 'buttons.1', src: 'assets/images/buttons/ladybug-red-button.png' },
      { id: 'buttons.2', src: 'assets/images/buttons/ladybug-blue-button.png' },
      { id: 'buttons.3', src: 'assets/images/buttons/ladybug-fuchsia-button.png' },
      { id: 'buttons.4', src: 'assets/images/buttons/ladybug-yellow-button.png' },
      { id: 'buttons.5', src: 'assets/images/buttons/ladybug-green-button.png' },
      { id: 'buttons.b', src: 'assets/images/buttons/flower-button.png' },
      { id: 'buttons.default', src: 'assets/images/buttons/fourleaf-button.png' },
      { id: 'icons.info', src: 'assets/images/icons/info-icon.png' },
      { id: 'icons.audio', src: 'assets/images/icons/audio-icon.png' },
      { id: 'statuses.1', src: 'assets/images/statuses/ladybug-red-status.png' },
      { id: 'statuses.2', src: 'assets/images/statuses/ladybug-blue-status.png' },
      { id: 'statuses.3', src: 'assets/images/statuses/ladybug-fuchsia-status.png' },
      { id: 'statuses.4', src: 'assets/images/statuses/ladybug-yellow-status.png' },
      { id: 'statuses.5', src: 'assets/images/statuses/ladybug-green-status.png' },
      { id: 'statuses_table.1', src: 'assets/images/statuses/ladybug-red-status.png' },
      { id: 'statuses_table.2', src: 'assets/images/statuses/ladybug-blue-status.png' },
      { id: 'statuses_table.3', src: 'assets/images/statuses/ladybug-fuchsia-status.png' },
      { id: 'statuses_table.4', src: 'assets/images/statuses/ladybug-yellow-status.png' },
      { id: 'statuses_table.5', src: 'assets/images/statuses/ladybug-green-status.png' },
      { id: 'tiles.1', src: 'assets/images/tiles/ladybug-red-tile.png' },
      { id: 'tiles.2', src: 'assets/images/tiles/ladybug-blue-tile.png' },
      { id: 'tiles.3', src: 'assets/images/tiles/ladybug-fuchsia-tile.png' },
      { id: 'tiles.4', src: 'assets/images/tiles/ladybug-yellow-tile.png' },
      { id: 'tiles.5', src: 'assets/images/tiles/ladybug-green-tile.png' },
      { id: 'images.logo', src: 'assets/images/logo-alpha.png' },
      { id: 'bonus.item.bee', src: 'assets/images/bonus/bonus-item-bee.png' },
      { id: 'bonus.item.ladybug', src: 'assets/images/bonus/bonus-item-ladybug.png' },
      { id: 'bonus.pointer', src: 'assets/images/bonus/bonus-pointer.png' },
      { id: 'bonus.round-fourleaf.brown', src: 'assets/images/bonus/bonus-round-fourleaf-brown.png' },
      { id: 'bonus.round-fourleaf.yellow', src: 'assets/images/bonus/bonus-round-fourleaf-yellow.png' },
      { id: 'bonus.round-fourleaf.green', src: 'assets/images/bonus/bonus-round-fourleaf-green.png' },
      { id: 'flare-sprite', src: 'assets/images/flare.png' },
      { id: 'flower-outcome-dx', src: 'assets/images/flower_outcome_dx.png' },
      { id: 'rays', src: 'assets/images/rays.png' },
    ],
    sounds: [
      { id: 'background', src: 'assets/sounds/lucky_bgm.mp3' },
    ],
    spritesheets: [
      { id: 'background', src: 'assets/spritesheets/background.json' },
      { id: 'giant', src: 'assets/spritesheets/giant.json' },
      { id: 'girl', src: 'assets/spritesheets/girl.json' },
      { id: 'kid', src: 'assets/spritesheets/kid.json' },
      { id: 'robot', src: 'assets/spritesheets/robot.json' },
      { id: 'tiger', src: 'assets/spritesheets/tiger.json' },
      { id: 'flower-ok', src: 'assets/spritesheets/flower-ok.json' },
      { id: 'ladybug-ok', src: 'assets/spritesheets/ladybug-ok.json' },
      { id: 'ladybug-eyeblink', src: 'assets/spritesheets/ladybug-eyeblink.json' },
      { id: 'ladybug_tile.1', src: 'assets/spritesheets/ladybug_tile_1.json' },
      { id: 'ladybug_tile.2', src: 'assets/spritesheets/ladybug_tile_2.json' },
      { id: 'ladybug_tile.3', src: 'assets/spritesheets/ladybug_tile_3.json' },
      { id: 'ladybug_tile.4', src: 'assets/spritesheets/ladybug_tile_4.json' },
      { id: 'ladybug_tile.5', src: 'assets/spritesheets/ladybug_tile_5.json' },
    ],
  },
};
